devices:
- id: heater
  name: Heizstab
  type: shelly_plug
  ip: 10.0.0.26
  port: 80
  power: 300
  priority: MEDIUM
  can_control: true
  min_runtime: 30
  enabled: true
  room: ''
  category: heating
  notes: ''
  last_seen: '2026-01-21T19:58:50.528202'
- id: pump
  name: Zirkulationspumpe
  type: shelly_plug
  ip: 10.0.0.24
  port: 80
  power: 10
  priority: MEDIUM
  can_control: true
  min_runtime: 0
  enabled: true
  room: ''
  category: ''
  notes: ''
  discovered_at: '2026-01-21T20:00:29.084996'
  last_seen: '2026-01-21T20:00:29.085043'
